workspace:
  base: /build
  path: src/github.com/ukhomeoffice/postgrest

pipeline:
  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t postgrest:$${DRONE_COMMIT_SHA} .
    when:
      event: push


  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/postgrest
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch: master
      event: push

  deploy_to_dev_transaction:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - TRANSACTION_DEV_NAME
      - TRANSACTION_DEV_DOMAIN
      - TRANSACTION_DEV_PROTOCOL
      - TRANSACTION_DEV_WHITELIST
      - TRANSACTION_DEV_KUBE_NAMESPACE
      - TRANSACTION_DEV_KUBE_SERVER
      - TRANSACTION_DEV_KUBE_TOKEN
      - TRANSACTION_DEV_INTERNAL_CA_URL
      - TRANSACTION_DEV_NO_LOGGING_URL_PARAMS
      - TRANSACTION_DEV_NO_LOGGING_BODY
      - TRANSACTION_DEV_NO_LOGGING_RESPONSE
      - TRANSACTION_DEV_PGRST_DB_URI
      - TRANSACTION_DEV_PGRST_DB_ANON_ROLE
      - TRANSACTION_DEV_PGRST_JWT_AUD
      - TRANSACTION_DEV_PGRST_ROLE_CLAIM_KEY
      - TRANSACTION_DEV_PGRST_DB_SCHEMA
      - TRANSACTION_DEV_PGRST_SECRET_IS_BASE64
      - TRANSACTION_DEV_PGRST_SERVER_PROXY_URI
      - TRANSACTION_DEV_KEYCLOAK_URL
      - TRANSACTION_DEV_KEYCLOAK_REALM
      - TRANSACTION_DEV_PRIVATE_UI_NAME
      - TRANSACTION_DEV_PRIVATE_WORKFLOW_ENGINE_NAME
      - TRANSACTION_DEV_PRIVATE_WORKFLOW_EXECUTOR_NAME
      - TRANSACTION_DEV_PRIVATE_TRANSLATION_SERVICE_NAME
      - TRANSACTION_DEV_UPTIME
    commands:
      - export NAME=$${TRANSACTION_DEV_NAME}
      - export DOMAIN=$${TRANSACTION_DEV_DOMAIN}
      - export PROTOCOL=$${TRANSACTION_DEV_PROTOCOL}
      - export WHITELIST=$${TRANSACTION_DEV_WHITELIST}
      - export KUBE_NAMESPACE=$${TRANSACTION_DEV_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${TRANSACTION_DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${TRANSACTION_DEV_KUBE_TOKEN}
      - export INTERNAL_CA_URL=$${TRANSACTION_DEV_INTERNAL_CA_URL}
      - export NO_LOGGING_URL_PARAMS=$${TRANSACTION_DEV_NO_LOGGING_URL_PARAMS}
      - export NO_LOGGING_BODY=$${TRANSACTION_DEV_NO_LOGGING_BODY}
      - export NO_LOGGING_RESPONSE=$${TRANSACTION_DEV_NO_LOGGING_RESPONSE}
      - export PGRST_DB_URI=$${TRANSACTION_DEV_PGRST_DB_URI}
      - export PGRST_DB_ANON_ROLE=$${TRANSACTION_DEV_PGRST_DB_ANON_ROLE}
      - export PGRST_JWT_AUD=$${TRANSACTION_DEV_PGRST_JWT_AUD}
      - export PGRST_ROLE_CLAIM_KEY=$${TRANSACTION_DEV_PGRST_ROLE_CLAIM_KEY}
      - export PGRST_DB_SCHEMA=$${TRANSACTION_DEV_PGRST_DB_SCHEMA}
      - export PGRST_SECRET_IS_BASE64=$${TRANSACTION_DEV_PGRST_SECRET_IS_BASE64}
      - export PGRST_SERVER_PROXY_URI=$${TRANSACTION_DEV_PGRST_SERVER_PROXY_URI}
      - export KEYCLOAK_URL=$${TRANSACTION_DEV_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${TRANSACTION_DEV_KEYCLOAK_REALM}
      - export PRIVATE_UI_NAME=$${TRANSACTION_DEV_PRIVATE_UI_NAME}
      - export PRIVATE_WORKFLOW_ENGINE_NAME=$${TRANSACTION_DEV_PRIVATE_WORKFLOW_ENGINE_NAME}
      - export PRIVATE_WORKFLOW_EXECUTOR_NAME=$${TRANSACTION_DEV_PRIVATE_WORKFLOW_EXECUTOR_NAME}
      - export PRIVATE_TRANSLATION_SERVICE_NAME=$${TRANSACTION_DEV_PRIVATE_TRANSLATION_SERVICE_NAME}
      - export UPTIME=$${TRANSACTION_DEV_UPTIME}
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch:
        - master
      event:
        - push

  deploy_to_demo_transaction:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - TRANSACTION_DEMO_NAME
      - TRANSACTION_DEMO_DOMAIN
      - TRANSACTION_DEMO_PROTOCOL
      - TRANSACTION_DEMO_WHITELIST
      - TRANSACTION_DEMO_KUBE_NAMESPACE
      - TRANSACTION_DEMO_KUBE_SERVER
      - TRANSACTION_DEMO_KUBE_TOKEN
      - TRANSACTION_DEMO_INTERNAL_CA_URL
      - TRANSACTION_DEMO_NO_LOGGING_URL_PARAMS
      - TRANSACTION_DEMO_NO_LOGGING_BODY
      - TRANSACTION_DEMO_NO_LOGGING_RESPONSE
      - TRANSACTION_DEMO_PGRST_DB_URI
      - TRANSACTION_DEMO_PGRST_DB_ANON_ROLE
      - TRANSACTION_DEMO_PGRST_JWT_AUD
      - TRANSACTION_DEMO_PGRST_ROLE_CLAIM_KEY
      - TRANSACTION_DEMO_PGRST_DB_SCHEMA
      - TRANSACTION_DEMO_PGRST_SECRET_IS_BASE64
      - TRANSACTION_DEMO_PGRST_SERVER_PROXY_URI
      - TRANSACTION_DEMO_KEYCLOAK_URL
      - TRANSACTION_DEMO_KEYCLOAK_REALM
      - TRANSACTION_DEMO_PRIVATE_UI_NAME
      - TRANSACTION_DEMO_PRIVATE_WORKFLOW_ENGINE_NAME
      - TRANSACTION_DEMO_PRIVATE_WORKFLOW_EXECUTOR_NAME
      - TRANSACTION_DEMO_PRIVATE_TRANSLATION_SERVICE_NAME
      - TRANSACTION_DEMO_UPTIME
    commands:
      - export NAME=$${TRANSACTION_DEMO_NAME}
      - export DOMAIN=$${TRANSACTION_DEMO_DOMAIN}
      - export PROTOCOL=$${TRANSACTION_DEMO_PROTOCOL}
      - export WHITELIST=$${TRANSACTION_DEMO_WHITELIST}
      - export KUBE_NAMESPACE=$${TRANSACTION_DEMO_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${TRANSACTION_DEMO_KUBE_SERVER}
      - export KUBE_TOKEN=$${TRANSACTION_DEMO_KUBE_TOKEN}
      - export INTERNAL_CA_URL=$${TRANSACTION_DEMO_INTERNAL_CA_URL}
      - export NO_LOGGING_URL_PARAMS=$${TRANSACTION_DEMO_NO_LOGGING_URL_PARAMS}
      - export NO_LOGGING_BODY=$${TRANSACTION_DEMO_NO_LOGGING_BODY}
      - export NO_LOGGING_RESPONSE=$${TRANSACTION_DEMO_NO_LOGGING_RESPONSE}
      - export PGRST_DB_URI=$${TRANSACTION_DEMO_PGRST_DB_URI}
      - export PGRST_DB_ANON_ROLE=$${TRANSACTION_DEMO_PGRST_DB_ANON_ROLE}
      - export PGRST_JWT_AUD=$${TRANSACTION_DEMO_PGRST_JWT_AUD}
      - export PGRST_ROLE_CLAIM_KEY=$${TRANSACTION_DEMO_PGRST_ROLE_CLAIM_KEY}
      - export PGRST_DB_SCHEMA=$${TRANSACTION_DEMO_PGRST_DB_SCHEMA}
      - export PGRST_SECRET_IS_BASE64=$${TRANSACTION_DEMO_PGRST_SECRET_IS_BASE64}
      - export PGRST_SERVER_PROXY_URI=$${TRANSACTION_DEMO_PGRST_SERVER_PROXY_URI}
      - export KEYCLOAK_URL=$${TRANSACTION_DEMO_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${TRANSACTION_DEMO_KEYCLOAK_REALM}
      - export PRIVATE_UI_NAME=$${TRANSACTION_DEMO_PRIVATE_UI_NAME}
      - export PRIVATE_WORKFLOW_ENGINE_NAME=$${TRANSACTION_DEMO_PRIVATE_WORKFLOW_ENGINE_NAME}
      - export PRIVATE_WORKFLOW_EXECUTOR_NAME=$${TRANSACTION_DEMO_PRIVATE_WORKFLOW_EXECUTOR_NAME}
      - export PRIVATE_TRANSLATION_SERVICE_NAME=$${TRANSACTION_DEMO_PRIVATE_TRANSLATION_SERVICE_NAME}
      - export UPTIME=$${TRANSACTION_DEMO_UPTIME}
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch:
        - master
      event:
        - deployment
