---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.NAME}}
spec:
  podSelector:
    matchLabels:
      name: {{.NAME}}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-external
  - from:
      - podSelector:
          matchLabels:
            name: {{.PRIVATE_UI_NAME}}
  - from:
      - podSelector:
          matchLabels:
            name: {{.PRIVATE_TRANSLATION_SERVICE_NAME}}
  - from:
      - podSelector:
          matchLabels:
            name: {{.PRIVATE_WORKFLOW_EXECUTOR_NAME}}
  - from:
      - podSelector:
          matchLabels:
            name: {{.PRIVATE_WORKFLOW_ENGINE_NAME}}
    ports:
    - protocol: TCP
      port: 10443