---
apiVersion: v1
kind: Secret
metadata:
  name: {{.NAME}}
type: Opaque
data:
  uri: {{.PGRST_DB_URI}}
  anonRole: {{.PGRST_DB_ANON_ROLE}}
  jwtAud: {{.PGRST_JWT_AUD}}
  jwtRoleClaimKey: {{.PGRST_ROLE_CLAIM_KEY}}